name: Deploy

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  merge:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: myapp-qa    
      steps:
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v3
        with:
          name: github-pages
  
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./merged-shards
  
      - name: Upload HTML report
        uses: actions/upload-pages-artifact@v2
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: github-pages
          retention-days: 14
   
  deployment:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2 
