name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  tests:
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/node.yml@main
    with:
      username: interceptorxx
    # secrets:
    #   token: ${{ secrets.envPAT }}

  tests-setup:
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/tests.yml@main
    with:
      username: interceptorxx
    # secrets:
    #   token: ${{ secrets.envPAT }}

  reporter:
    needs: tests
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/deploy.yml@main
    with:
      username: interceptorxx
    # secrets:
    #   token: ${{ secrets.envPAT }}
