name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/node.yml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}

    tests-setup:
      name: 'Setup Tests'
      runs-on: ubuntu-latest
      uses: interceptorxx/interceptorxx.github.io/.github/workflows/tests.yml@main
      with:
        username: interceptorxx
      secrets:
        token: ${{ secrets.envPAT }}

  reporter:
    name: 'Reporter'
    runs-on: ubuntu-latest
    needs: tests
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/deploy.yml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}
