name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: ./.github/workflows/install.yml
      - name: Setup Tests
        uses: ./.github/workflows/tests.yml

  reporter:
    name: 'Reporter'
    runs-on: ubuntu-latest
    needs: tests  
    steps:
      - name: Deploy
        uses: ./.github/workflows/deploy.yml
