name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

concurrency:
  group: 'pages'
  cancel-in-progress: true


jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: interceptorxx/interceptorxx.github.io/.github/workflows/node.yml@main
      - name: Setup Tests
        uses: interceptorxx/interceptorxx.github.io/.github/workflows/tests.yml@main
  reporter:
    name: 'Reporter'
    runs-on: ubuntu-latest
    needs: tests  
    steps:
      - name: Deploy
        uses: interceptorxx/interceptorxx.github.io/.github/workflows/deploy.yml@main
