name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  install:
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/node.yaml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}

  prepare:
    needs: install
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/tests.yaml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}

  reporter:
    needs: prepare
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/deploy.yaml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}
