name: Main

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  runs:
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/node.yaml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}

  execute:
    needs: runs
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/tests.yaml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}

  reporter:
    needs: execute
    uses: interceptorxx/interceptorxx.github.io/.github/workflows/deploy.yaml@main
    with:
      username: interceptorxx
    secrets:
      token: ${{ secrets.envPAT }}
