name: Install Node

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  node:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: myapp-qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pnpm
        id: cached-dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            ./
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.run_id }}-${{ github.run_number }}

      - name: Debug Cache Hit
        run: echo "Cache Hit - ${{ steps.cached-dependencies.outputs.cache-hit }}"

      - name: Debug Directory Structure
        run: |
          pwd
          ls -a

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm with Node.js 20
        run: npm install -g pnpm

      - name: Install dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Debug
        run: |
          pwd
          ls -a  # Check if files are listed without detailed information
          ls -alA



          
      # - name: Cache pnpm
      #   id: pnpm-lock-id
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ./
      #     key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       pnpm-${{ runner.os }}-build
      #       pnpm-${{ runner.os }}-
        
