name: Install Node

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  node:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: myapp-qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: |
            ./
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-
      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm with Node.js 20
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Debug
        run: |
          pwd
          ls -a  # Check if files are listed without detailed information
          ls -alA
