name: Install Node and Run Playwright Tests

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

defaults: 
  run:
    working-directory: myapp-qa

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Cache pnpm
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ./myapp-qa
      #     key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       pnpm-${{ runner.os }}-build
      #       pnpm-${{ runner.os }}-


      # - name: Restore cache
      #   id: restore-cached-dependencies
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: |
      #       ./myapp-qa
      #     key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}   

      # - name: Cache dependencies
      #   id: save-cached-dependencies
      #   if: steps.restore-cached-dependencies.outputs.cache-hit != 'true'
      #   uses: actions/cache/save@v3
      #   with:
      #     path: |
      #       ./myapp-qa
      #     key: ${{ steps.restore-cached-dependencies.outputs.cache-primary-key }}
          
      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        if: steps.restore-cached-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Debug Installed Dependencies
        run: |
          pwd
          ls -a
          ls -alA
        
  # tests:
  #   needs: install
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Restore cache
  #       id: restore-cached-dependencies
  #       uses: actions/cache/restore@v3
  #       with:
  #         path: |
  #           ./myapp-qa
  #         key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

  #     - name: Run your tests
  #       run: npx playwright test src/
        
  #     - name: Upload Playwright report
  #       uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: myapp-qa/playwright-report
  #         retention-days: 30
