name: Tests

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myapp-qa    
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Restore cache
        id: restore-cached-dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ./myapp-qa
          key: ${{ steps.restore-cached-dependencies.outputs.cache-primary-key }}

      - name: Debug Cache Key
        run: echo "Cache Key - ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}"
      
      - name: Run your tests
        run: npx playwright test src/
        
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: myapp-qa/playwright-report
          retention-days: 30
      
      - name: Debug Paths
        run: |
          pwd
          ls -a  # Check if files are listed without detailed information
          ls -alA
