name: Tests

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myapp-qa    
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug Paths
        run: |
          pwd
          ls -a  # Check if files are listed without detailed information
          ls -alA
          
      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cached-dependencies
        with:
          path: |
            ./
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.run_id }}-${{ github.run_number }}
      
      - name: Debug Cache Hit
        run: echo "Cache Hit - ${{ steps.cached-dependencies.outputs.cache-hit }}"

      - name: Run your tests
        run: npx playwright test src/
        
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: myapp-qa/playwright-report
          retention-days: 30
