name: Tests

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myapp-qa
    steps:
      - name: Run your tests
        run: npx playwright test myapp-qa/src/
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: github-pages
          path: myapp-qa/playwright-report
          retention-days: 30
