name: Playwright Tests and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    defaults:
      run:
        working-directory: myapp-qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm with Node.js 18
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run your tests
        run: npx playwright test myapp-qa/src/
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: myapp-qa/playwright-report
          retention-days: 30

  release:
    name: Release Playwright
    runs-on: ubuntu-latest
    needs: playwright
    outputs:
      artifact_path: ${{ needs.playwright.outputs.artifact_path }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
      - name: Test Artifact
        run: ls -R

  deploy:
    needs: playwright
    environment:
      name: playwright-report
      url: https://interceptorxx.github.io/
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
