name: Tests

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myapp-qa
    steps:
      - name: Print Node.js and npm versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"
      - name: Print npx path
        run: echo "npx is located at $(command -v npx)"
      - name: Run your tests
        run: npx playwright test myapp-qa/src/
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: github-pages
          path: myapp-qa/playwright-report
          retention-days: 30
