name: Tests

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myapp-qa    
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug
        run: |
          pwd
          ls -a  # Check if files are listed without detailed information
          ls -alA
      - name: Run your tests
        run: npx playwright test myapp-qa/src/
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: github-pages
          path: myapp-qa/playwright-report
          retention-days: 30

          
    # steps:
    #   - name: Debug working directory
    #     run: ls
      # - name: Run your tests
      #   run: npx playwright test myapp-qa/src
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: github-pages
      #     path: myapp-qa/playwright-report
      #     retention-days: 30
